default: &default
  adapter: mysql2
  port: 3306
  pool: 10
  timeout: 5000
  encoding: utf8
  host: localhost
  username: <username>
  password: <password>

<% { development: 'dev', test: 'test', production: 'prod' }.each do |k, v| %>
<%= k %>:
  <<: *default
  database: edukasyon_ph_<%= v %>
<% end %>